sudo: required
services:
    - docker
    
before_install:
    - docker build -t ionutbz/docker-react -f Dockerfile.dev .
    
script:
    - docker run ionutbz/docker-react npm run test -- --coverage
    